name: cwb
channels:
  - conda-forge
dependencies:
  - matplotlib
  - scikit-learn
  - jupyter
  - seaborn
  - python=3.11
  - imbalanced-learn
  - biopython
  - pytorch::pytorch
  - pandas
  - conda-forge::rdkit
  - conda-forge::gemmi
  - anaconda::networkx
  - numpy>=1.26.4,<1.27.0
